### ISSUE TITLE
Add ARGB format

### ISSUE THREAD

**Issue by garug** [elchininet/ColorTranslator#106]
Despite the name, this format is like HEXA but swaped, #AARRGGBB

**Comment by elchininet** [comment]
Hi @garug,

This library follows the CSS Color Module, and for hex values it uses its [hex notation](https://www.w3.org/TR/2022/CRD-css-color-4-20221101/#hex-notation). It is impossible to introduce the format that you are proposing because the library recognises automatically the format of the inputs and if you use `#00FFFFFF` it is impossible to know if it is a `cyan` color fully opaque or a `white` color fully transparent. For your use case, you can obtain the format that you want in multiple ways, this is one proposal that could work for you:

```javascript
const toARGB = (color) => {
    const regExp = /([\da-f]{2})/gi;
    const m = ColorTranslator.toHEXA(color).match(regExp);
    return `#${m[3]}${m[0]}${m[1]}${m[2]}`;
};

toARGB('red') // #FFFF0000
toARGB('rgba(255, 0, 255, 0.5)'); // #7FFF00FF
```

**Comment by elchininet** [comment]
Hi @garug,
Did you try my proposal?
Closing this issue because it is something that cannot be implemented.
Regards.

**Comment by garug** [comment]
Late comment, I opted to ignore alpha in application for now but your proposal would work perfectly for my use case!! You rocks!
